#  Повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
print(a := np.linspace(12, 24, 12, endpoint=False))

[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a = a.reshape(6, 2)
b = a.reshape(3, 4)
c = a.reshape(12, 1)
d = a.reshape(1, 12)
e = a.reshape(2, 6)

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
print(a:= a.reshape(6, -1))
print(b:= a.reshape(-1, 4))
print(c:= a.reshape(12, -1))
print(d:= a.reshape(-1, 12))
print(e:= a.reshape(2, -1))

[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]
[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]
[[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]]
[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: Нет, т.к. одномерный массив состоит из 1 строки.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [58]:
print('Двумерно: \n{}\n'.format(m1 := np.random.randn(3, 4)))
print('Одномерно: \n{}\n'.format(m2 :=  m1.flatten()))

Двумерно: 
[[-0.75981627 -2.80454239 -0.12636276  0.26772426]
 [ 2.22857088  0.8635829   0.0841352   0.40549193]
 [ 0.42916012  0.46589708 -0.27453189  1.58499016]]

Одномерно: 
[-0.75981627 -2.80454239 -0.12636276  0.26772426  2.22857088  0.8635829
  0.0841352   0.40549193  0.42916012  0.46589708 -0.27453189  1.58499016]



6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [6]:
print(a := np.arange(20, 0, -2))

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [7]:
print('Це будет двумерный массив, а а был одномерный: {}'.format(b := np.arange(20, 1, -2).reshape(1, 10)))

Це будет двумерный массив, а а был одномерный: [[20 18 16 14 12 10  8  6  4  2]]


8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [20]:
a = np.zeros((3, 2))
b = np.ones((2, 2))

print(c := np.vstack((a, b)).size)

10


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [76]:
print('Исходное: \n{}\n'.format(a := np.arange(0, 12).reshape(4, 3)))
print('Транспонированное: \n{}\n'.format(At := a.T))
print('Умноженное: {}\n'.format(b := a.dot(At)))
print(f'Размер матрицы: {b.size}\n')
print(f'Определитель матрицы b = {np.linalg.det(b)}, поэтому обратную не получится сделать.')

Исходное: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Транспонированное: 
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

Умноженное: [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

Размер матрицы: 16

Определитель матрицы b = 0.0, поэтому обратную не получится сделать.


10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [83]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [92]:
print(c := np.random.randint(0, 16, 16))

[13  5  5  9  3  5 12 14  1  9 11  1  9 13  3 13]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [93]:
print(C := c.reshape(4, 4))

[[13  5  5  9]
 [ 3  5 12 14]
 [ 1  9 11  1]
 [ 9 13  3 13]]


In [99]:
print(D := b + C * 10)
print(f'\nОпределитель: {np.linalg.det(D)} \nРанг: {np.linalg.matrix_rank(D)} \nОбратная матрица:\n {np.linalg.inv(D)}')

[[135  64  73 122]
 [ 44 100 206 262]
 [ 33 176 259 222]
 [122 252 242 432]]

Определитель: -441631199.9999996 
Ранг: 4 
Обратная матрица:
 [[ 0.00965249 -0.00115572  0.00017453 -0.00211471]
 [-0.00222937 -0.0133775   0.00596226  0.00567886]
 [ 0.0028988   0.00436527  0.00540659 -0.00624449]
 [-0.00304933  0.00568456 -0.00655597  0.00309743]]
